In [ ]:
import numpy as np
from random import sample
import matplotlib.pyplot as plt
import math
import cv2
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
img = cv2.imread('/content/drive/My Drive/Colab Notebooks/lena.bmp', )
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
int_img = np.zeros(img.shape)
#plt.imshow(gray,cmap='gray')
#plt.show()

In [ ]:
def integral_image(img):
  intimg = np.zeros(img.shape)
  for i in range(img.shape[0]):
    for j in range(img.shape[1]):
      intimg[i,j] = np.sum(img[:i+1,:j+1])
  return intimg
def integral_image2(img):
  img = img.astype(np.int32)
  img = np.pad(img, ((1,0),(1,0)), constant_values=0)
  for i in range(1,img.shape[0]):
    for j in range(1,img.shape[1]):
      img[i,j] = img[i,j-1] + img[i-1,j] - img[i-1,j-1] + img[i,j]
  return img




In [ ]:
import time
a = np.ones([5,5])
int_a = integral_image(a)
t1 = time.time()
#int_gray = integral_image(gray)
t2 = time.time()
int_gray2 = integral_image2(gray)
t3 = time.time()
int_gray3 = cv2.integral(gray)
t4 = time.time()
#print(int_gray)
print(int_gray2)
print(int_gray3)
print(t2-t1)
print(t3-t2)
print(t4-t3)

[[       0        0        0 ...        0        0        0]
 [       0      144      176 ...    66762    66919    66928]
 [       0      176      272 ...   132958   133173   133200]
 ...
 [       0    64592   127984 ... 33166927 33233286 33293189]
 [       0    64723   128121 ... 33231400 33298008 33358098]
 [       0    64893   128375 ... 33296722 33363536 33423859]]
[[       0        0        0 ...        0        0        0]
 [       0      144      176 ...    66762    66919    66928]
 [       0      176      272 ...   132958   133173   133200]
 ...
 [       0    64592   127984 ... 33166927 33233286 33293189]
 [       0    64723   128121 ... 33231400 33298008 33358098]
 [       0    64893   128375 ... 33296722 33363536 33423859]]
1.6450881958007812e-05
0.2993628978729248
0.00042891502380371094


In [ ]:
type(int_gray2[511,511])
int_gray3.shape

(513, 513)